# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Live My Life
subtitle: 淡而无味也是一种味道
author: Mr.Vincent
language: en
timezone:


# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://v-vincen.life    # Note: don't forget to modify the CNAME file to your url
# url: https://v_vincen.gitee.io/    # Note: don't forget to modify the CNAME file to your url
root: /
# root: https://cdn.jsdelivr.net/gh/V-Vincen/V-Vincen.github.io/
permalink: :year/:month/:day/:title/
permalink_defaults:



#Custom Setting Start

# Site settings
SEOTitle: JavaDev | 一如Java深似海
email: 601521821@qq.com
description: "It's an IT blog..."
keyword: "Java,v-vincen,v-vincen,livemylife,IT  blog,Blog"
header-img: img/header_img/newhome_bg.jpg
archives-img: img/header_img/archive_bg2.jpg

# Favicon settings
favicon: img/avatar/favicon.jpg

# Signature Setup
signature: true # show signature
signature-img: img/signature/vincent-white.png


# Wave settings
# wave: true    # show wave

# WaveOverLay settings
waveoverlay: true


# SNS Settings
# RSS: true
github_username: V-Vincen
twitter_username: V_Vincen_
instagram_username: v_vincen_
# facebook_username:  yourAccount
# linkedin_username:  yourAccount
# zhihu_username: WVincen
weibo_username: WVincen


# Sidebar Settings
sidebar: true   # whether or not using Sidebar.
sidebar-about-description: "I don't know where I am going ,but I am on my way..."
sidebar-avatar: img/avatar/vincnet.jpg    # use absolute URL, seeing it's used in both `/` and `/about/`
widgets:
- visitor   # busuanzi: https://busuanzi.ibruce.info/
- featured-tags
- short-about
- recent-posts
- friends-blog
- archive
- category

# widget behavior
## Archive
archive_type: 'monthly'
show_count: true

## Featured Tags
featured-tags: true   # whether or not using Feature-Tags
featured-condition-size: 0    # A tag will be featured if the size of it is more than this condition value


## Friends
friends: [
    {
        title: "Teacher Ye",
        href: "http://teacherye.com/"
    },{
        title: "Ray",
        href: "https://tianhualiang2019.github.io/"
    },{
        title: "GoldenaArcher",
        href: "https://goldenaarcher.github.io/"
    },{
        title: "鸢羽_颖",
        href: "https://www.cnblogs.com/guoyinghome/"
    },{
        title: "十八岁的夏天",
        href: "https://www.cnblogs.com/xiaofengwang/"
      }
]


# Comment Settings

## Gitalk Settings
## Doc:https://github.com/gitalk/gitalk/blob/master/readme-cn.md
##
gitalk:
  owner: V-Vincen
  admin: V-Vincen
  repo: test-comment
  clientID: c81ff43219a616c193e0
  clientSecret: 17312e25a3b3c592824c813bd537140f48ee2fcf
  # repo: blog-comment
  # clientID: c5c071e55f689f41560d
  # clientSecret: 1e8aabf73ccb26e519ee937ea1ddd241c5d13b79
  perPage: 10
  pagerDirection: last
  createIssueManually: false
  language: en
  maxCommentHeight: 250



## Gitment Settings
## Doc:https://github.com/imsun/gitment
##
# gitment:
  # owner: V-Vincen
  # repo: test-comment
  # client_id: c81ff43219a616c193e0
  # client_secret: 17312e25a3b3c592824c813bd537140f48ee2fcf

  # repo: blog-comment
  # client_id: c5c071e55f689f41560d
  # client_secret: 1e8aabf73ccb26e519ee937ea1ddd241c5d13b79

  # desc:
  # perPage: 10
  # maxCommentHeight: 250


## valine Settings
## https://valine.js.org/
##
# valine:
#   API_ID: FSJ1zn7oYNyOFi3KTSzu7uE7-gzGzoHsz
#   API_Key: YcwQKKzaMzulSIVJAVMpA78F
#   placeholder: Say something ...
#   guest_info: nick,mail,link #评论者相关属性
#   avatar: monsterid  #头像设置
#   pageSize: 10
#   language: zh-cn

## valine_deserts Settings
## Doc:https://deserts.io/diy-a-comment-system/
## Doc:https://deserts.io/valine-admin-document/
##
# valine_deserts:
#   API_ID: FSJ1zn7oYNyOFi3KTSzu7uE7-gzGzoHsz
#   API_Key: YcwQKKzaMzulSIVJAVMpA78F
#   placeholder: Write a Comment
#   pageSize: 10
#   language: en


## Disqus settings
##
# disqus_username: your-disqus-ID


# Analytics settings
# Baidu Analytics
ba_track_id: 49e5faf2bfd6c26c1eb20bad10ef10c7

# Google Analytics
ga_track_id: UA-164526897-1   # Format: UA-xxxxxx-xx

#sitemap
sitemap:
  path: sitemap.xml

# Custom Setting End


# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:


# Writing
new_post_name: :title.md    # File name of new posts
default_layout: post
auto_spacing: true
titlecase: false    # Transform title into titlecase
external_link: true   # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: true
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:


# Category & Tag
default_category: uncategorized
category_map:
tag_map:
home_posts_tag: true    # show posts tags


# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
##
date_format: YYYY-MM-DD
time_format: HH:mm:ss


# Pagination
## Set per_page to 0 to disable pagination
##
per_page: 10
pagination_dir: archives

archive_generator:
  per_page: 10
  yearly: true
  monthly: true
  daily: false


# Markdown-it config
## Docs: https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki
##
markdown:
  render:
    html: true
    xhtmlOut: false
    breaks: true
    linkify: true
    typographer: true
    quotes: '“”‘’'


# Build Settings
anchorjs: true    # if you want to customize anchor. check out line:186 of `post.ejs`

# article top
top: true

# WordCount Settings
## Dependencies: https://github.com/willin/hexo-wordcount
## Docs: https://www.npmjs.com/package/hexo-wordcount
##
wordcount: true


# top scroll progress
scroll: true


# Tip
tip:
  enable: true
  copyright: If you like this blog or find it useful for you, you are welcome to comment on it. You are also welcome to share this blog, so that more people can participate in it. If the images used in the blog infringe your copyright, please contact the author to delete them. Thank you !


# Social Share Post
## Docs:https://github.com/overtrue/share.js
##
socialshare: true


# Viewer config
## Docs:https://github.com/fengyuanchen/viewer
## Demo:https://fengyuanchen.github.io/viewer/
##
viewer: true


# ThemeColor config
themecolor: true


# Extensions
## Plugins: https://hexo.io/plugins/

# Search Setting
## Search:https://go.kieran.top/post/45/
## Dependencies: https://github.com/SuperKieran/hexo-generator-search-zip
##
search:
  path: search.json
  zipPath: search.flv
  versionPath: searchVersion.json
  field: post
  trigger: auto   # if 'auto', trigger search by changing input;if 'manual', trigger search by pressing enter key or search button
  top_n_per_article: 1    # show top n results per article, show all results by setting to -1


# Theme config
## Themes: https://hexo.io/themes/
##
theme: livemylife


# Gitter
## Docs:https://gitter.im/?utm_source=left-menu-logo
##
gitter:
  room: hexo-theme-livemylife/blog


# Deployment
## Docs: https://hexo.io/docs/deployment.html
##
deploy:
  type: git
  repository: https://github.com/V-Vincen/V-Vincen.github.io.git
  # repository: git@gitee.com:V_Vincen/V_Vincen.git
  # repository: https://gitee.com/V_Vincen/V_Vincen.git
  branch: master
